
import { Geist, Geist_Mono} from "next/font/google";
import { Tajawal } from "next/font/google";
import "./globals.css";
import Header from "./pages/header/header";
import Footer from "./pages/footer/footer";
import { ContextProvider } from "@/Context/context";
import { Toaster } from 'react-hot-toast'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const tajawal = Tajawal({
  variable: "--font-tajawal",
  subsets: ["arabic", "latin"],
  weight: ["200","300","400","500","700","800","900"]
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "tadbeer.sa",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {




  return (
    <html lang="en">
      <head>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${tajawal.variable} antialiased`}
      >
        <Toaster position="top-center" />
        <ContextProvider>
        <Header />
        {children}
        <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
